src/Entity/Comment.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="comments")
 * @ORM\HasLifecycleCallbacks()
 * @ORM\Entity(repositoryClass="App\Repository\CommentRepository")
 */
class Comment
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    public $created_at;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Video", inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $video;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }


    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getVideo(): ?Video
    {
        return $this->video;
    }

    public function setVideo(?Video $video): self
    {
        $this->video = $video;

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\TypeUser;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\RadioType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichImageType;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class)
            ->add('description', TextareaType::class)
            ->add('type', ChoiceType::class,[
                'choices' => [
                    'NATURE' => 'nature',
                    'ÉTUDIANT' => 'étudiant',
                    'COACH' => 'coach',
                    'FORMATEUR'   => 'formateur',
                    'ÉDITEUR' => 'éditeur',
                    'ADMINISTRATEUR' => 'administrateur',
                ]
            ])
            ->add('icon', VichImageType::class,[
                'required' => false,
                'allow_delete' => false,
                'download_label' => '...',
                'download_uri' => false,
                'image_uri' => true
            ])
            ->add('color', RadioType::class,[
                'required' => false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => TypeUser::class,
        ]);
    }
}

src/Controller/UserController.php
<?php
namespace App\Controller;

use App\Entity\delete;
use App\Entity\Contact;
use App\Entity\Classe;
use App\Form\ClasseType;
use App\Form\ContactType;
use App\Repository\ClasseRepository;
use App\Repository\FormationRepository;
use App\Repository\UserRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
/**
 * @Route("/{_locale}/admin/")
 */
class UserController extends AbstractController
{
    /**
     * List all type of users and allow admin to add new users
     * @Route("typeUser", name="type_user")
     */
    public function typeUser() {

        return $this->render('user/type_user.html.twig',['toggled' => true]);
    }
    /**
     * @Route("membres", name="membres")
     * @Route("membres/{classId}", name="membres")
     */
    public function membres($classId = null, UserRepository $usersRepo, Request $request, ObjectManager $manager, ClasseRepository $classeRepository, FormationRepository $formationRepository) {

        //to optimize this fucntion get user by class and remove the test in the view
        $users     = $usersRepo->findAll();
        $listClass = $classeRepository->findAll();
        $formations = $formationRepository->findAll();
        $currentCalss = $classeRepository->findOneBy(['id' => $classId]);
        $class = new Classe();
        $form  = $this->createForm(ClasseType::class, $class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $manager->persist($class);

            $manager->flush();

            return $this->redirectToRoute('membres',['classId' => $classId]);
        }
        return $this->render('user/type_member.html.twig', ['users' => $users,'listClass' => $listClass, 'currentCalss' => $currentCalss,'formations' => $formations, 'form' => $form->createView()]);
    }

    /**
     * Affact user to a specific class
     * @Route("affectUserClass/", name="affect_user_class")
     */
    public function affectUserClass(Request $request, ObjectManager $manager, UserRepository $userRepo, ClasseRepository $classeRepository) {

        $userId  =  $request->get('userId');

        $classIds =  $request->get('selectedClass');
        $user  = $userRepo->findOneBy(['id' => $userId ]);

        if(!empty($classIds)) {
            foreach ($classIds as $classId) {
                $newClass = $classeRepository->findOneBy(array('id' => $classId));
                if($newClass) {
                    //affect the class for the new user
                    $user->addClasse($newClass);
                    $manager->persist($user);
                    $manager->flush();
                }
            }
        } else {
            $classes = $classeRepository->findAll();
            foreach ($classes as $class) {
                $user->removeClasse($class);
                $manager->persist($user);
                $manager->flush();
            }
        }

        return new Response(
            'success'
        );

    }

    /**
     * @Route("addMembers/", name="add_members")
     */
    public function addMembers(ClasseRepository $classeRepository, FormationRepository $formationRepository ) {

        $formations = $formationRepository->findAll();
        $classes    = $classeRepository->findAll();
        return $this->render('user/add_member.html.twig', [
            'formations' => $formations,
            'classes'    => $classes,
        ]);
    }

    /**
     * @Route("Code", name="code")
     */
    public function codes() {

        return $this->render('user/code.html.twig',['toggled' => true]);
    }
    /**
     * get list of users acoording to the given ruls if the param role is empty return list off all users
     * @Route("getUsers/{role}", name="users_list")
     */
    public function getUsers(UserRepository $repo, $role = null) {
        if($role) {
            $users = $repo->findByRole($role);
        } else {
            $users = $repo->findAll();
        }

        /*switch ($role) {
            case "1": $type = "admin";
            case "2": $type = "user";
            case "3": $type = "editor";
            case "4": $type = "coach";
            case "5" : $type = "formator";
            default: $type = "user";
        }*/
        //get list of all users

        return $this->render('user/list-user.html.twig',['users' => $users]);
    }

    /**
     * @Route("updateCounter", name="update_counter")
     */
    public function updateCounter(Request $request, ObjectManager $manager, UserRepository $repo) {
        $counter      = $request->request->get('counter');
        $current_user = $this->getUser();
        if($current_user) {
            $oldCounter = $current_user->getCounter();
            $tmstamp = strtotime($oldCounter) + strtotime($counter);
            $current_user->setCounter(date("H:m:s", $tmstamp));
            $manager->persist( $current_user);
            $manager->flush();
            return new Response(
                'success'
            );
        } else {
            return new Response(
                'error'
            );
        }
    }

    /**
     * List all type of users and allow admin to add new users
     * @Route("invitationcode", name="admin_invitationcode")
     */
    public function typeInvitationcode() {

        return $this->render('user/invitationcode.html.twig',['toggled' => true]);
    }
    /**
     * List all type of users and allow admin to add new users
     * @Route("userclass", name="admin_userclass")
     */
    public function typeuserclass() {

        return $this->render('user/userclass.html.twig',['toggled' => true]);
    }


    /**
     * List all type of users and allow admin to add new users
     * @Route("Member", name="admin_member")
     */
    public function typeMember($classId = null, UserRepository $usersRepo, Request $request, ObjectManager $manager, ClasseRepository $classeRepository) {
        //to optimize this fucntion get user by class and remove the test in the view
        $users     = $usersRepo->findAll();
        $listClass = $classeRepository->findAll();
        $currentCalss = $classeRepository->findOneBy(['id' => $classId]);
        $class = new Classe();
        $form  = $this->createForm(ClasseType::class, $class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $manager->persist($class);

            $manager->flush();

            return $this->redirectToRoute('membres',['classId' => $classId]);
        }
        return $this->render('user/type_member.html.twig', ['users' => $users,'listClass' => $listClass, 'currentCalss' => $currentCalss, 'form' => $form->createView()]);
        //return $this->render('user/type_member.html.twig',['toggled' => true]);
    }
    /**
     * @Route("Contact", name="contact")
     */
    public function contact(ObjectManager $manager, Request $request, \Swift_Mailer $mailer) {
        $contact = new Contact();
        $form = $this->createForm(ContactType::class, $contact);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $manager->persist($contact);

            $manager->flush();

            $message = (new \Swift_Message('Bonjour !'))
                ->setFrom($contact->getMail())
                ->setTo('informatique@kiwi-ins  titute.com')
                ->setBody(
                    $contact->getMessage());
            $mailer->send($message);
            return $this->redirectToRoute('type_user');
        }
        return $this->render('contact/contact_admin.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * Affect users to a specific classes
     * @Route("affectUsersClasses/", name="affect_users_classes")
     */
    public function affectUsersClasses(Request $request, ObjectManager $manager, UserRepository $userRepo, ClasseRepository $classeRepository) {
        $usersIds  =  $request->get('userIds');
        $uselectedClass =  $request->get('selectedClass');
        foreach ($usersIds as $userId) {
            $user  = $userRepo->findOneBy(['id' => $userId ]);
            foreach ($uselectedClass as $classId) {
                $newClass = $classeRepository->findOneBy(array('id' => $classId));
                if($newClass) {
                    //affect the class for the new user
                    $user->addClasse($newClass);
                    $manager->persist($user);
                    $manager->flush();
                }
            }
        }

        return new Response(
            'success'
        );

    }

    /**
     * Affect users to a specific formations
     * @Route("affectUsersFormations", name="affect_users_formation")
     */
    public function affectUsersFormations(Request $request, ObjectManager $manager, UserRepository $userRepo, FormationRepository $formationRepository) {

        $usersIds  =  $request->get('userIds');
        $selectedFormation =  $request->get('selectedFormation');
        foreach ($usersIds as $userId) {
            $user  = $userRepo->findOneBy(['id' => $userId ]);
            foreach ($selectedFormation as $formationId) {
                $newFormation = $formationRepository->findOneBy(array('id' => $formationId));
                if($newFormation) {
                    //affect the class for the new user
                    $user->addFormationsSup($newFormation);
                    $manager->persist($user);
                    $manager->flush();
                }
            }
        }

        return new Response(
            'success'
        );

    }

    /**
     * @Route("kitKiwi", name="kit_kiwi")
     */
    public function kitKiwi() {
        return $this->render('admin/kit_Kiwi.html.twig');
    }
}

templates/user/code.html.twig
{% extends 'baseUser.html.twig' %}
{% block title %} Codes d'invitation - Kiwi Institute {% endblock %}
{% block top_title %} Codes d'invitation {% endblock %}
{% block body %}
    <div class="d-flex vh-100">
        <div class="container m-auto">
            <img class="customimagencours" src="{{ asset('images/site-en-cours.svg') }}"/>
            <img class="customimagencours"  src="{{ asset('images/site-en-cours-2.svg') }}"/>
        </div>
    </div>
{% endblock %}

templates/user/contact.html.twig
 {% extends 'base.html.twig' %}
{% block body %}

    <div class="login">
        <div class="wrapper wrapper-signup">
            <div class="container container-signup">
                <h3 class="text-center">Inscrire vous</h3>
                {{ form_start(form) }}
                <div class="login-form">
                    <label class="field a-field a-field_a1 page__field">
                        {{ form_widget(form.username, {'attr':{'placeholder':'NOM','class':"field__input a-field__input form-group"}}) }}
                        <small class="text-danger">
                            {{form_errors(form.username) }}
                        </small>
                    </label>
                    <label class="field a-field a-field_a1 page__field">
                        {{ form_widget(form.lastname, {'attr':{'placeholder':'PRÉNOM','class':"field__input a-field__input form-group"}}) }}
                        <small lass="text-danger">
                            {{form_errors(form.lastname) }}
                        </small>
                    </label>
                    <label class="field a-field a-field_a1 page__field">
                        {{ form_widget(form.email,{'attr':{'placeholder':'MAIL','class':"field__input a-field__input form-group"}}) }}
                        <small class="text-danger">
                            {{form_errors(form.email) }}
                        </small>
                    </label>
                    <label class="field a-field a-field_a1 page__field show-pass-1">
                        {{ form_widget(form.password.first,{'attr':{'placeholder':'MOT DE PASSE','class':"field__input a-field__input form-group"}}) }}
                        <div class="show-password"> <i class="fas fa-eye"></i>
                        </div>
                    </label>
                     <small class="text-danger">
                            {{form_errors(form.password.first) }}
                        </small>
                    <label class="field a-field a-field_a1 page__field show-pass-2">
                        {{ form_widget(form.password.second,{'attr':{'placeholder':'CONFIRMER MOT DE PASSE','class':"field__input a-field__input form-group"}}) }}
                        <small class="text-danger">
                            {{form_errors(form.password.second) }}
                        </small>
                        <div class="show-password"> <i class="fas fa-eye"></i> </div>
                    </label>
                    <div class="custom-control custom-checkbox small">
                        <input type="checkbox" class="custom-control-input" id="accept-terms">
                        <label class="custom-control-label text-white" for="accept-terms">j'ai lu et j'accepte les termes et conditions  </label>
                    </div>
                </div>
                <hr>
                <div class="form-group text-center">
                    <button type="submit" class="btn btn-secondary btn-user" disabled>ENREGISTRER</button>
                </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/user/invitationcode.html.twig
{% extends 'baseUser.html.twig' %}
{% block top_title %} Dashboard {% endblock %}
{% block body %}
    <div class="d-flex vh-100">
        <div class="container m-auto">
            <img class="customimagencours" src="{{ asset('images/site-en-cours.svg') }}"/>
            <img class="customimagencours"  src="{{ asset('images/site-en-cours-2.svg') }}"/>
        </div>
    </div>
{% endblock %}

templates/user/list-user.html.twig
{% extends 'baseUser.html.twig' %}
{% block top_title %} TYPES D’UTILISATEURS {% endblock %}
{% block body %}
    <div class="row mr-2">
        <div class="col-12">
            <a class="btn btn-primary float-right p-2" href="{{ path('new_type_user') }}">Créer un nouveau type d'utilisateur</a>
        </div>
    </div>

    <div class="row row pr-0 mr-0">
        <div class="col-12 py-2">
                <div class="full-card shadow py-2 mt-4">
                    <div class="card-header py-3">
                        <div class="custom-control custom-checkbox small">
                            <input type="checkbox" class="custom-control-input" id="checkAll">
                            <label class="custom-control-label" for="checkAll">Tout Sélectionner </label>
                            <div class="btn-action version-2">
                                <button type="button" class="btn btn-download btn-link btn-sm" rel="tooltip" data-toggle="modal" data-target="#delete-selected-user" title="Supprimer les utilisateurs selectionnées"  data-path="{{ path('delete_notes')}}">
                                    <img src="{{ asset('images/icons/trash-small.png') }}">
                                </button>
                                <label class="green-switch">
                                    <input type="checkbox"  class="activate_all_user">
                                    <span class="slider round"></span>
                                </label>
                            </div>
                        </div>
                    </div>
                <div class="card-body">
                    <div class="table-responsive custom-table">
                        <table class="table" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th class="nosort"></th>
                                <th>Nom</th>
                                <th>Prénom</th>
                                <th>Pseudonyme</th>
                                <th>Temps passé sur la plateforme</th>
                                <th>Type d'utilisateur</th>
                                <th>Date d’ajout à la plateforme</th>
                                <th>Activer/desactiver</th>
                                <th>Dernière connexion</th>
                                <th class="nosort"></th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for user in users %}
                                <tr>
                                    <td>
                                        <div class="custom-control custom-checkbox small">
                                            <input type="checkbox" class="custom-control-input check-element"  name="user_check"  id="user_{{ user.id }}" name="user-{{ user.id }}" data-id="{{ user.id }}" value="">
                                            <label class="custom-control-label" for="user_{{ user.id }}"></label>
                                        </div>
                                    </td>
                                    <td>{{ user.username }}</td>
                                    <td>{{ user.lastname }}</td>
                                    <td>{{ user.pseudo }}</td>
                                    <td>{{ user.pseudo }}</td>
                                    <td>
                                        {% set roles = "" %}
                                        {%  for role in user.roles %}
                                            {%  set roles = roles ~ functions_manager.get_roles(role) ~ ', ' %}
                                        {% endfor %}
                                        {{ roles|trim(', ') }}
                                    </td>
                                    <td>{{ user.createdAt |date("d M, Y")}}</td>
                                    <td>
                                        <label class="green-switch">
                                            <input type="checkbox" {% if  user.active == 1 %}checked {% endif %} class="activate-user" data-id="{{ user.id }}">
                                            <span class="slider round"></span>
                                        </label>
                                    </td>
                                    <td>{{ user.pseudo }}</td>
                                    <td class="td-actions text-right" >
                                        <a href="{{ path('user_profile',{'id': user.id}) }}" rel="tooltip" title="Voir profile" class="btn btn-vu btn-link btn-sm" >  <i class="fas fa-eye"></i></a>
                                        <a href="" rel="tooltip" data-toggle="modal" data-target="#delete-user" title="Supprimer utilisateur" class="btn btn-vu btn-link btn-sm modal-delete-user" data-id="{{ user.id }}"> <img src=" {{ asset('images/icons/trash-xs.png') }}"></a>
                                    </td>
                                </tr>
                            {% endfor %}
                           </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- modal delete user -->
    <div class="modal fade" id="delete-user" tabindex="-1" role="dialog" aria-labelledby="delete-user" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Supprimer cette utilisateur</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Êtes-vous sûr de vouloir supprimer cet utilisateur ?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Non</button>
                    <a href="#" class="btn btn-primary delete-user">Oui</a>
                </div>
            </div>
        </div>
    </div>
    <!-- end modal delete user -->

    <!-- modal delete selected user -->
    <div class="modal fade" id="delete-selected-user" tabindex="-1" role="dialog" aria-labelledby="delete-selected-user" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Supprimer les utilisateurs selectionnées</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Êtes-vous sûr de vouloir supprimer ces utilisateurs ?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Non</button>
                    <a href="#" class="btn btn-primary" id="delete-selected-user">Oui</a>
                </div>
            </div>
        </div>
    </div>
    <!-- end modal delete selected user -->
{% endblock %}

templates/user/testselect2.html.twig
{% block stylesheets %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2-bootstrap-css/1.4.6/select2-bootstrap.min.css">

<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/css/select2.min.css" rel="stylesheet" />
{% endblock %}
{% block javascripts %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.2.1/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/js/select2.min.js"></script>
<script>
    $(document).ready(function() {
    $(".js-select2").select2({
        closeOnSelect : false,
        placeholder : "Placeholder",
        // allowHtml: true,
        allowClear: true,

    });
    });
</script>
{% endblock %}
{% block body %}
<div class="container">
    <div class="row">
        <h4>checkbox</h4>
        <select class="js-select2" multiple="multiple">
            <option value="O1" data-badge="">Option1</option>
            <option value="O2" data-badge="">Option2</option>
            <option value="O3" data-badge="">Option3</option>
            <option value="O4" data-badge="">Option4</option>
            <option value="O5" data-badge="">Option5</option>
            <option value="O6" data-badge="">Option6</option>
            <option value="O7" data-badge="">Option7</option>
        </select>
    </div>
    {% endblock %}

templates/user/userclass.html.twig
{% extends 'baseUser.html.twig' %}
{% block top_title %} Dashboard {% endblock %}
{% block body %}
    <div class="d-flex vh-100">
        <div class="container m-auto">
            <img class="customimagencours" src="{{ asset('images/site-en-cours.svg') }}"/>
            <img class="customimagencours"  src="{{ asset('images/site-en-cours-2.svg') }}"/>
        </div>
    </div>
{% endblock %}